import {
    Trophy,
    Home,
    Settings,
    FileText,
    Lightbulb,
    Brain,
    Bug,
    User,
    Users,
    Check,
    Coins,
    Moon,
    X,
    Flame,
    Dices,
    Globe,
    Handshake,
    Baby,
    Keyboard,
    Lock,
    Pencil,
    Plus,
    Bot,
    MessageSquare,
    Shell,
    Timer,
    Sun,
    MessageCircle,
    Crown,
    Eraser,
    Brush,
    GraduationCap,
    HelpCircle,
    Languages,
    Palette
} from 'lucide-svelte';

export const lucideMap: Record<string, any> = {
    'trophy': Trophy,
    'house': Home,
    'gear': Settings,
    'memo': FileText,
    'light_bulb': Lightbulb,
    'brain': Brain,
    'bug': Bug,
    'bust_in_silhouette': User,
    'busts_in_silhouette': Users,
    'check_mark_button': Check,
    'coin': Coins,
    'coins': Coins,
    'crescent_moon': Moon,
    'cross_mark': X,
    'crown': Crown,
    'fire': Flame,
    'game_die': Dices,
    'globe_showing_europe_africa': Globe,
    'handshake': Handshake,
    'hatching_chick': Baby,
    'keyboard': Keyboard,
    'locked': Lock,
    'pencil': Pencil,
    'plus': Plus,
    'robot': Bot,
    'speech_balloon': MessageSquare,
    'spiral_shell': Shell,
    'stopwatch': Timer,
    'sun': Sun,
    'thought_balloon': MessageCircle,
    '1st_place_medal': Trophy,
    '2nd_place_medal': Trophy,
    '3rd_place_medal': Trophy,
    'broom': Eraser,
    'brush': Brush,
    'graduation_cap': GraduationCap,
    'help_circle': HelpCircle,
    'languages': Languages,
    'palette': Palette
};
